// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2KPzK6qN-cpaSQ4R_EiL80Z5Q5CMCwd8',
    appId: '1:631007728535:web:d7bd5db8b64f572d342ad2',
    messagingSenderId: '631007728535',
    projectId: 'alakhcar-8e4e1',
    authDomain: 'alakhcar-8e4e1.firebaseapp.com',
    databaseURL: 'https://alakhcar-8e4e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alakhcar-8e4e1.appspot.com',
    measurementId: 'G-2FPLHPLJ5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQuVo2mAfWU2I2Bl7BZfCxpq-RYLA86gY',
    appId: '1:631007728535:android:87ba67c6c0459146342ad2',
    messagingSenderId: '631007728535',
    projectId: 'alakhcar-8e4e1',
    databaseURL: 'https://alakhcar-8e4e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alakhcar-8e4e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHCai0RzukwQWWjfKP_Ok5ZKHAm8XMRtA',
    appId: '1:631007728535:ios:e18ed544aa180c81342ad2',
    messagingSenderId: '631007728535',
    projectId: 'alakhcar-8e4e1',
    databaseURL: 'https://alakhcar-8e4e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alakhcar-8e4e1.appspot.com',
    iosClientId: '631007728535-l1a623rhg6ck5pqt7hl1i2qgdh399k6s.apps.googleusercontent.com',
    iosBundleId: 'com.lionode.alakhcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHCai0RzukwQWWjfKP_Ok5ZKHAm8XMRtA',
    appId: '1:631007728535:ios:89746b530dba3359342ad2',
    messagingSenderId: '631007728535',
    projectId: 'alakhcar-8e4e1',
    databaseURL: 'https://alakhcar-8e4e1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alakhcar-8e4e1.appspot.com',
    iosClientId: '631007728535-42mv34s00qq90420ihaejso39pqm0sbd.apps.googleusercontent.com',
    iosBundleId: 'com.lionode.alakhCar',
  );
}
